### ISSUE TITLE
Could you please publish the 1.6.2 library version?

### ISSUE THREAD

**Issue by lboue** [adafruit/Adafruit_Protomatter#79]
Hello,

Could you please publish the 1.6.2 library version? Indeed the last commit ca4f876 was 3 months ago.
https://github.com/adafruit/Adafruit_Protomatter/blob/ca4f8764bedea915d4b9d85df1b57b6860bd7103/library.properties#L2

This version fixes this issue: [Not compatible with esp32 version 3.0.0 #78](https://github.com/adafruit/Adafruit_Protomatter/issues/78)

- Arduino board:  ADAFRUIT_MATRIXPORTAL_ESP32S3

- Arduino IDE version (found in Arduino -> About Arduino menu):  2.3.2

- List the steps to reproduce the problem below: 
Build pixeldust.ino

**Comment by lboue** [comment]
Hello,

Can I have a response?

Regards

**Comment by tannewt** [comment]
I've published 1.7.0
